name: CI/CD to Cloud Run

on:
  push:
    branches: [ "main" ]
  # or specify whichever branches or events trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Check out code
        uses: actions/checkout@v3

        # 3) Authenticate to Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 

      # 4) Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gcloud beta

      # 5) Build & push Docker image to Google Container Registry (GCR)
      #    or Artifact Registry. Adjust the registry URL as needed.
      - name: Build and push image
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/back-habit-tracker/htk-api:latest

      # 6) Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy htk-api \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/back-habit-tracker/htk-api:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
